# Generated by Django 6.0.4 on 2026-04-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('officer', 'Placement Officer')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(default=0.0)),
                ('backlogs', models.IntegerField(default=0)),
                ('coding_score', models.IntegerField(default=0)),
                ('aptitude_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('internships', models.IntegerField(default=0)),
                ('certifications', models.IntegerField(default=0)),
                ('github_contributions', models.IntegerField(default=0)),
                ('leetcode_solved', models.IntegerField(default=0)),
                ('hackathon', models.IntegerField(default=0)),
                ('soft_skills', models.IntegerField(default=0)),
                ('resume_score', models.IntegerField(default=0)),
                ('github_score', models.IntegerField(default=0)),
                ('placement_probability', models.FloatField(default=0.0)),
                ('placement_month', models.IntegerField(default=12)),
                ('company_matches', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
