# Generated by Django 6.0.4 on 2026-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='aptitude_exam_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='aptitude_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/aptitude/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='backlog_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/backlogs/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='certification_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='cgpa_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/cgpa/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='coding_platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='coding_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='coding_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='communication_certificate',
            field=models.FileField(blank=True, null=True, upload_to='proofs/communication/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='hackathon_certificate',
            field=models.FileField(blank=True, null=True, upload_to='proofs/hackathon/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='hackerrank_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to='proofs/internship/'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='project_repo_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='soft_skills_basis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
